# require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

source 'https://github.com/CocoaPods/Specs.git'

# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

use_hermes = ENV['USE_HERMES'] == nil || ENV['USE_HERMES'] == '1'

# DGSwiftUtilities
should_install_locally = ENV['SHOULD_INSTALL_DEV_LIBRARIES_LOCALLY'] == '1'
library_path_DGSwiftUtilities = ENV['PATH_DEV_LIBRARY_SWIFT_UTILITIES']
should_install_locally_DGSwiftUtilities = should_install_locally && library_path_DGSwiftUtilities && File.exist?(library_path_DGSwiftUtilities)

# ComputableLayout
library_path_ComputableLayout = ENV['PATH_DEV_LIBRARY_COMPUTABLE_LAYOUT']
should_install_locally_ComputableLayout = should_install_locally && library_path_ComputableLayout && File.exist?(library_path_ComputableLayout)

# VisualEffectBlurView
library_path_VisualEffectBlurView = ENV['PATH_DEV_LIBRARY_VISUAL_EFFECT_BLUR_VIEW']
should_install_locally_VisualEffectBlurView = should_install_locally && library_path_VisualEffectBlurView && File.exist?(library_path_VisualEffectBlurView)



puts "\nreact-native-ios-visual-effect-view - example"
puts " - hermes_enabled: #{use_hermes}"
puts " - linkage: #{linkage}"
puts " - SHOULD_INSTALL_DEV_LIBRARIES_LOCALLY: #{should_install_locally}"
puts " - PATH_DEV_LIBRARY_SWIFT_UTILITIES: #{library_path_DGSwiftUtilities}"
puts " - should_install_locally_DGSwiftUtilities: #{should_install_locally_DGSwiftUtilities}"
puts " - PATH_DEV_LIBRARY_VISUAL_EFFECT_BLUR_VIEW: #{library_path_VisualEffectBlurView}"
puts " - should_install_locally_VisualEffectBlurView: #{should_install_locally_VisualEffectBlurView}"
puts "\n"

target 'IosVisualEffectViewExample' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  if should_install_locally_DGSwiftUtilities
    pod 'DGSwiftUtilities', :path => library_path_DGSwiftUtilities
  end

  if should_install_locally_ComputableLayout
    pod 'ComputableLayout', :path => library_path_ComputableLayout
  end

  if should_install_locally_VisualEffectBlurView
    pod 'VisualEffectBlurView', :path => library_path_VisualEffectBlurView
  end

  target 'IosVisualEffectViewExampleTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
  end
end
