
export type BlendMode = 
  | 'color'
  | 'colorBurn'
  | 'colorDodge'
  | 'darken'
  | 'difference'
  | 'divide'
  | 'exclusion'
  | 'hardLight'
  | 'hue'
  | 'lighten'
  | 'linearBurn'
  | 'linearDodge'
  | 'linearLight'
  | 'luminosity'
  | 'multiply'
  | 'overlay'
  | 'pinLight'
  | 'saturation'
  | 'screen'
  | 'softLight'
  | 'subtract'
  | 'vividLight';